# Generated by Django 4.1.2 on 2022-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
