# Generated by Django 4.1.2 on 2022-11-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='electricity_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='media/electricity_receipts/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='rent_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='media/rent_receipts/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='water_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='media/water_receipts/'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/id_pic/'),
        ),
    ]
