# Generated by Django 4.1.2 on 2022-10-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0002_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
