# Generated by Django 4.1.2 on 2022-10-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0002_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_receipts', models.ImageField(default='default.jpg', upload_to='rent_receipts')),
                ('electricity_receipts', models.ImageField(default='default.jpg', upload_to='electricity_receipts')),
                ('water_receipts', models.ImageField(default='default.jpg', upload_to='water_receipts')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.AddField(
            model_name='details',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kola.customer'),
        ),
    ]
