# Generated by Django 4.1.2 on 2022-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0002_alter_detail_electricity_receipts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='electricity_receipts',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='rent_receipts',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='water_receipts',
        ),
        migrations.RemoveField(
            model_name='identification',
            name='id_picture',
        ),
        migrations.AddField(
            model_name='detail',
            name='electricity_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='water_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
