# Generated by Django 4.1.2 on 2022-11-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0003_remove_detail_electricity_receipts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
