# Generated by Django 4.1.2 on 2022-10-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0003_alter_customer_full_name_alter_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kola.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True)),
                ('id_picture', models.ImageField(default='default.jpg', upload_to='id_pics')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kola.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bills', models.CharField(choices=[('E', 'Electricity'), ('W', 'Water')], max_length=30, null=True)),
                ('electricity_picture', models.ImageField(default='default.jpg', upload_to='electricity_pics')),
                ('water_picture', models.ImageField(default='default.jpg', upload_to='water_pics')),
                ('bills_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kola.customer')),
            ],
        ),
    ]
