# Generated by Django 4.1.2 on 2022-10-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0004_rename_details_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
