# Generated by Django 4.1.2 on 2022-10-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0004_loan_identification_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
