# Generated by Django 4.1.2 on 2022-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0004_alter_detail_electricity_receipts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='electricity_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='rent_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='water_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
