# Generated by Django 4.1.2 on 2022-11-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0004_detail_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='id_pic/'),
        ),
    ]
