# Generated by Django 4.1.2 on 2022-11-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0005_identification_id_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='electricity_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='electricity_receipts/'),
        ),
        migrations.AddField(
            model_name='detail',
            name='rent_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='rent_receipts/'),
        ),
        migrations.AddField(
            model_name='detail',
            name='water_receipts',
            field=models.ImageField(blank=True, null=True, upload_to='water_receipts/'),
        ),
    ]
