# Generated by Django 4.1.2 on 2022-11-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kola', '0006_detail_electricity_receipts_detail_rent_receipts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='electricity_receipts',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='rent_receipts',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='water_receipts',
        ),
        migrations.RemoveField(
            model_name='identification',
            name='id_picture',
        ),
    ]
